org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.caching=true

## Environment
minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.21.2)
neoforge_version=21.1.240
neoforge_version_range=[21.1.240,)
loader_version_range=[4,)

## Mod
mod_id=tts
mod_name=Tube Transport System: Reforged
mod_license=LGPL-3.0-only
mod_version=0.6
mod_group=tubeTransportSystem
mod_authors=Alz454 (polyrobot), SrNadien
mod_description=Pneumatic tubes you ride yourself. Why should items get all the fun?
